baseURL = "https://pipa-pvc.bangunan.co/"
languageCode = "id"
title = "Pipa PVC Murah | Jual Genteng Beton, Genteng Keramik, Genteng Oven"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Dsitributor Pipa PVC berkualitas - Jual Pipa PVC berbagai ukuran dan merk dengan harga bersaing dan pengiriman cepat"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual pipa pvc", "pipa pvc murah", "pipa pvc berkualitas", "distributor pipa pvc", "pipa air pvc", "harga pipa pvc", "pvc berbagai ukuran"]
  base_price = 15000
  price_range = 5000
  free_shipping = true
  materials = [
  "Pipa PVC ukuran 1/2 inch",
  "Pipa PVC ukuran 3/4 inch",
  "Pipa PVC ukuran 1 inch",
  "Pipa PVC ukuran 2 inch",
  "Pipa PVC ukuran 3 inch",
  "Pipa PVC ukuran 4 inch"
  ]
  categories = ["Pipa PVC", "Material Konstruksi", "Distributor Pipa PVC"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika spesifikasi material tidak sesuai.",
  "Pengembalian gratis untuk barang yang tidak sesuai pesanan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Dsitributor Pipa PVC Berkualitas"
  hero_description = "Kami menawarkan berbagai jenis pipa PVC berkualitas dengan berbagai ukuran dan merk ternama. Solusi ideal untuk instalasi pipa air Anda, dengan bahan yang tahan lama dan harga terjangkau."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Pipa PVC"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan pipa PVC berkualitas tinggi dengan berbagai pilihan ukuran dan merk, harga bersaing, dan layanan pengiriman free ongkir. Gratis konsultasi untuk membantu Anda memilih pipa PVC yang tepat untuk kebutuhan instalasi Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "pipa-pvc.bangunan.co menawarkan berbagai jenis pipa PVC berkualitas dari merk-merk ternama. Kami mengutamakan kepuasan pelanggan dengan produk yang tahan lama, mudah dipasang, dan harga yang bersaing. Pilih kami untuk memenuhi kebutuhan instalasi pipa Anda dengan produk terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Fajar|Hendra|Agus|Samsul|Rio|Yudi}"
  message = "{Saya membeli pipa PVC dari pipa-pvc.bangunan.co untuk proyek {instalasi air|plumbing|perpipaan} di rumah saya, dan hasilnya {sangat memuaskan|luar biasa|menakjubkan}. Kualitas produk {sangat baik|berkualitas tinggi|premium} dan {tahan lama|awet|kokoh}.|Pipa PVC dari pipa-pvc.bangunan.co {sangat berkualitas|bermutu tinggi|kokoh} dan sesuai dengan kebutuhan {proyek|renovasi|instalasi} di rumah saya.}"
  response = "{Terima kasih atas {kepercayaan|pilihan} Anda! Kami {senang|gembira} dapat {menyediakan|menghadirkan} pipa PVC berkualitas untuk proyek Anda.|Kami {menghargai|berterima kasih atas} kepercayaan Anda dan senang bisa membantu proyek Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Maya|Ayu|Sari|Fitri|Lina|Diah|Nur}"
  message = "{pipa-pvc.bangunan.co {sangat membantu|mempermudah|memberikan solusi} dalam memilih pipa PVC untuk rumah saya. Produk yang saya {beli|pilih} {berkualitas|premium|bermutu} dan sesuai dengan {kebutuhan|keperluan} saya.|Saya {sangat terbantu|sangat puas} dengan pilihan pipa PVC dari pipa-pvc.bangunan.co. Kualitasnya {baik|tinggi|premium} dan tepat untuk kebutuhan saya.}"
  response = "{Kami sangat {menghargai|berterima kasih atas} ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan pipa PVC dari kami.|Kami sangat {menghargai|senang dengan} ulasan Anda. Terima kasih atas kepercayaannya.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Toni|Bayu|Gilang|Bambang|Faisal|Rizal|Ali|Ahmad|Rudi}"
  message = "{Produk pipa PVC dari pipa-pvc.bangunan.co {sangat berkualitas|berkualitas tinggi|premium} dan cocok untuk proyek {perumahan|konstruksi|pembangunan} saya. Proses pembelian dan pengirimannya juga {cepat|efisien|terorganisir}.|Pipa PVC dari pipa-pvc.bangunan.co {berkualitas|kokoh|premium} dan pengirimannya {cepat|efisien|terjamin} sesuai harapan.}"
  response = "{Terima kasih! Kami {berkomitmen|berdedikasi|fokus} untuk menyediakan pipa PVC berkualitas dengan {layanan terbaik|pelayanan prima}.|Kami {berterima kasih|senang} atas kepercayaan Anda dan terus berkomitmen memberikan yang terbaik.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Yanto|Toni|Faisal|Ari|Yoga|Agus|Gani|Dedi|Fajar}"
  message = "{Saya {sangat puas|senang|terkesan} dengan pipa PVC dari pipa-pvc.bangunan.co. Kualitasnya {sangat baik|terbaik|tahan lama} dan {kokoh|kuat|awet} untuk proyek saya.|Pipa PVC dari pipa-pvc.bangunan.co {sangat memuaskan|berkualitas tinggi|terbaik} dan sangat sesuai dengan {kebutuhan|keperluan} proyek saya.}"
  response = "{Senang mendengar Anda puas dengan pipa PVC kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami {menghargai|berterima kasih atas} kepercayaan Anda. Terima kasih telah memilih produk kami.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan pipa-pvc.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Produk pipa PVC yang saya {beli|pilih} {sangat berkualitas|bermutu tinggi|kokoh} dan sesuai dengan {harapan saya|ekspektasi saya|standar yang saya butuhkan}.|Saya {sangat puas|senang|terkesan} dengan pelayanan dari pipa-pvc.bangunan.co. Pipa PVC yang saya {gunakan|beli} {sangat berkualitas|bermutu tinggi|premium} dan {sesuai|ideal} dengan harapan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani|memenuhi kebutuhan} proyek Anda dengan pipa PVC terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah memilih produk kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Benny|Yudi|Galih|Iwan|Toni|Wawan|Rizky|Gani}"
  message = "{Pipa PVC dari pipa-pvc.bangunan.co {sangat sesuai|tepat|cocok} dengan kebutuhan proyek renovasi rumah saya. Proses pengirimannya {cepat|terjamin|aman} dan {baik|teratur|efisien}.|Saya {senang|puas|terkesan} dengan pipa PVC dari pipa-pvc.bangunan.co. Produk ini {sesuai|ideal} dan pengirimannya {cepat|aman|efisien}.}"
  response = "{Kami {senang|gembira|bahagia} mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {memilih|mempercayai} produk kami. Kami {gembira|senang} Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Pipa PVC 1/2 inch"
  price = "15.000 /pcs"
[[params.tabelItems]]
  name = "Pipa PVC 3/4 inch"
  price = "20.000 /pcs"
[[params.tabelItems]]
  name = "Pipa PVC 1 inch"
  price = "25.000 /pcs"
[[params.tabelItems]]
  name = "Pipa PVC 2 inch"
  price = "40.000 /pcs"
[[params.tabelItems]]
  name = "Pipa PVC 3 inch"
  price = "60.000 /pcs"
[[params.tabelItems]]
  name = "Pipa PVC 4 inch"
  price = "90.000 /pcs"

[params.appliList]
  "Pipa PVC 1/2 inch" = "instalasi saluran air kecil"
  "Pipa PVC 3/4 inch" = "saluran air sedang, distribusi air"
  "Pipa PVC 1 inch" = "saluran utama untuk distribusi air"
  "Pipa PVC 2 inch" = "pipa saluran pembuangan air"
  "Pipa PVC 3 inch" = "pipa saluran besar, untuk pabrik"
  "Pipa PVC 4 inch" = "instalasi saluran limbah besar"

[params.kegunaanList]
  "Pipa PVC 1/2 inch" = "digunakan untuk saluran air kecil di rumah"
  "Pipa PVC 3/4 inch" = "cocok untuk distribusi air di rumah dan bangunan"
  "Pipa PVC 1 inch" = "saluran utama air bersih di perumahan"
  "Pipa PVC 2 inch" = "untuk pembuangan air limbah"
  "Pipa PVC 3 inch" = "digunakan dalam pabrik untuk saluran air"
  "Pipa PVC 4 inch" = "instalasi besar untuk saluran limbah industri"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Dsitributor Pipa PVC Murah | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"